local rm = require("render-markdown")

vim.keymap.set('n', '<leader>mr',  function() rm.enable() end,      { desc = "[m] enable render-markdown" })
vim.keymap.set('n', '<leader>me',  function() rm.enable() end,      { desc = "[m] enable render-markdown" })
vim.keymap.set('n', '<leader>mbe', function() rm.buf_enable() end,  { desc = "[m] buffer enable" })
vim.keymap.set('n', '<leader>mdd', function() rm.disable() end,     { desc = "[m] disable render-markdown" })
vim.keymap.set('n', '<leader>mde', function() rm.buf_disable() end, { desc = "[m] buffer disable" })
vim.keymap.set('n', '<leader>mt', function() rm.toggle() end,      { desc = "[m] toggle render-markdown" })
vim.keymap.set('n', '<leader>mbt', function() rm.buf_toggle() end,  { desc = "[m] buffer toggle" })
vim.keymap.set('n', '<leader>mg',  function() rm.get() end,         { desc = "[m] get render-markdown state" })
vim.keymap.set('n', '<leader>ml',  function() rm.log() end,         { desc = "[m] log render-markdown" })
vim.keymap.set('n', '<leader>mx',  function() rm.expand() end,      { desc = "[m] expand markdown" })
vim.keymap.set('n', '<leader>mc',  function() rm.contract() end,    { desc = "[m] contract markdown" })
vim.keymap.set('n', '<leader>mdb', function() rm.debug() end,       { desc = "[m] debug render-markdown" })
vim.keymap.set('n', '<leader>mC',  function() rm.config() end,      { desc = "[m] config render-markdown" })
